/* empty css                      */(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const a of e)if(a.type==="childList")for(const s of a.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&n(s)}).observe(document,{childList:!0,subtree:!0});function o(e){const a={};return e.integrity&&(a.integrity=e.integrity),e.referrerPolicy&&(a.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?a.credentials="include":e.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function n(e){if(e.ep)return;e.ep=!0;const a=o(e);fetch(e.href,a)}})();const L="https://your-energy.b.goit.study/api";async function b(t,r={}){const o=`${L}${t}`,n=await fetch(o,{...r,headers:{"Content-Type":"application/json",...r.headers}});if(!n.ok){const e=new Error(`API error: ${n.status}`);throw e.status=n.status,e}return n.json()}async function $(t){return b(`/exercises/${t}`)}const q="your-energy-quote",h="your-energy-favorites";function _(){const t=new Date;return`${t.getFullYear()}-${String(t.getMonth()+1).padStart(2,"0")}-${String(t.getDate()).padStart(2,"0")}`}function v(){try{return JSON.parse(localStorage.getItem(h)||"[]")}catch{return[]}}function S(t){const r=v().filter(o=>o._id!==t);localStorage.setItem(h,JSON.stringify(r))}function c(t){const r=document.createElement("div");return r.textContent=t,r.innerHTML.replace(/"/g,"&quot;")}function d(t){const r=document.createElement("div");return r.textContent=t,r.innerHTML}function A(t){const r=Math.round(Number(t))||0;let o="";for(let n=1;n<=5;n++)o+=`<span class="exercise-card-rating-star ${n<=r?"filled":""}">★</span>`;return o}function x(){const t=document.querySelector("[data-quote-text]"),r=document.querySelector("[data-quote-author]"),o=_(),n=localStorage.getItem(q);if(n)try{const e=JSON.parse(n);if(e.date===o&&e.quote){t&&(t.textContent=e.quote),r&&(r.textContent=e.author||"");return}}catch{}t&&(t.textContent="Завантажте цитату на головній сторінці."),r&&(r.textContent="")}function p(){const t=document.querySelector("[data-favorites-list]"),r=document.querySelector("[data-favorites-empty]"),o=v();if(t){if(!o.length){t.innerHTML="",r&&(r.hidden=!1);return}r&&(r.hidden=!0),t.innerHTML=o.map(n=>`
    <li class="exercise-card">
      <img class="exercise-card-image" src="${c(n.gifUrl)}" alt="${c(n.name)}" loading="lazy" />
      <div class="exercise-card-body">
        <h3 class="exercise-card-name">${d(n.name)}</h3>
        <div class="exercise-card-rating">${A(n.rating)}</div>
        <p class="exercise-card-meta"><span>${d(n.bodyPart)}</span> <span>${d(n.target)}</span></p>
        <div class="exercise-card-footer">
          <span class="exercise-card-calories">${n.burnedCalories} cal</span>
          <span class="exercise-card-time">${n.time} min</span>
          <button type="button" class="exercise-card-start" data-exercise-id="${c(n._id)}">Start</button>
          <button type="button" class="exercise-card-remove" data-remove-id="${c(n._id)}" aria-label="Remove from favorites">&#10006;</button>
        </div>
      </div>
    </li>
  `).join(""),t.querySelectorAll(".exercise-card-start").forEach(n=>{n.addEventListener("click",()=>O(n.getAttribute("data-exercise-id")))}),t.querySelectorAll(".exercise-card-remove").forEach(n=>{n.addEventListener("click",()=>{S(n.getAttribute("data-remove-id")),p()})})}}const i=document.querySelector("[data-modal-backdrop]"),u=document.querySelector("[data-modal-content]"),l=document.querySelector("[data-modal-close]");function y(){i&&(i.hidden=!0),document.body.style.overflow=""}function O(t){if(!i||!u)return;u.innerHTML='<div class="modal-loading">Loading...</div>',i.hidden=!1,document.body.style.overflow="hidden";const r=()=>{l==null||l.removeEventListener("click",r),i==null||i.removeEventListener("click",o),document.removeEventListener("keydown",n),y()},o=e=>{e.target===i&&r()},n=e=>{e.key==="Escape"&&r()};l==null||l.addEventListener("click",r),i==null||i.addEventListener("click",o),document.addEventListener("keydown",n),$(t).then(e=>{const a=v().some(E=>E._id===e._id);u.innerHTML=`
        <img class="modal-exercise-image" src="${c(e.gifUrl)}" alt="${c(e.name)}" />
        <h2 class="modal-exercise-name" id="modal-title">${d(e.name)}</h2>
        <p class="modal-exercise-meta">${d(e.bodyPart)} • ${d(e.target)} • ${e.burnedCalories} cal • ${e.time} min</p>
        <p class="modal-exercise-description">${d(e.description||"")}</p>
        <button type="button" class="modal-exercise-fav" data-remove-from-fav data-exercise-id="${c(e._id)}">Remove from Favorites</button>
      `;const s=u.querySelector("[data-remove-from-fav]");s&&a?s.addEventListener("click",()=>{S(e._id),y(),p()}):s&&s.remove()},()=>{u.innerHTML='<div class="modal-loading">Failed to load exercise.</div>'})}x();p();const f=document.querySelector("[data-burger]"),m=document.querySelector("[data-header-menu]");f&&m&&(f.addEventListener("click",()=>{const t=m.classList.toggle("is-open");f.setAttribute("aria-expanded",t)}),m.querySelectorAll(".header__nav-link").forEach(t=>{t.addEventListener("click",()=>{m.classList.remove("is-open"),f.setAttribute("aria-expanded","false")})}));const g=window.location.pathname;document.querySelectorAll(".header__nav-link").forEach(t=>{const r=t.getAttribute("href"),o=r==="./index.html"&&!g.includes("favorites")||r==="./favorites.html"&&g.includes("favorites");t.classList.toggle("header__nav-link--current",o)});
//# sourceMappingURL=favorites.js.map
